#!/usr/bin/env python3

import os
import argparse
from verstak_parser import VDocument


def main(in_path: str, out_path: str, tipograf_enabled: bool, allow_header_links: bool):
    if os.path.isdir(in_path):
        if not os.path.isdir(out_path):
            os.makedirs(out_path)
        print(f"Listing directory {in_path}")
        process_directory(in_path, out_path, tipograf_enabled, allow_header_links)
    elif os.path.isfile(in_path):
        if not os.path.isdir(out_path):
            os.makedirs(out_path)
        process_file(in_path, out_path, tipograf_enabled, allow_header_links)
    else:
        print(f"Error: {in_path} doesn't exist")


def process_file(in_path: str, out_path: str, tipograf_enabled: bool, allow_header_links: bool):
    doc = os.path.basename(in_path)
    print(f"Started parsing {in_path}")
    document = VDocument.from_file(f"{in_path}")
    if tipograf_enabled:
        document.do_typograf()
    document.store_html(f"{out_path}{os.sep}{doc}.html", allow_header_links=allow_header_links)
    print(f"Finished parsing {in_path}")
    print(f"Output file: {out_path}{os.sep}{doc}.html")


def process_directory(in_path: str, out_path: str):
    docs = os.listdir(in_path)
    i = 1
    for doc in docs:
        if not doc.startswith(".") and not doc.startswith("~") and doc.endswith("docx"):
            print(f"Started parsing  ({i}/{len(docs)}): {doc}")
            document = VDocument.from_file(f"{in_path}{os.sep}{doc}")
            document.do_typograf()
            document.store_html(f"{out_path}{os.sep}{doc}.html")
            print(f"Finished parsing ({i}/{len(docs)}): {doc}")
        i += 1
    print(f"Done {in_path}")
    print(f"Files are stored in {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Make html from docx.')
    parser.add_argument('input', metavar='in', type=str,
                        help='Input file/directory', default=f'{os.getcwd()}{os.sep}docs')
    parser.add_argument('output', metavar='out', type=str, nargs='?',
                        help='Output directory', default=f"{os.getcwd()}{os.sep}")
    parser.add_argument('-t', dest='tipograf_enabled', action='store_false',
                        help='Disable tipograf')
    parser.add_argument('-ah', dest='allow_header_links', action='store_true',
                        help='Allow links in headers/titles')
    args = parser.parse_args()
    main(args.input, args.output, args.tipograf_enabled, args.allow_header_links)
